# Generated by Django 5.0.6 on 2024-05-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(related_name='task', to='todo.tag'),
        ),
    ]
